version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - chromadb_data:/app/chromadb
      - ./google-credentials.json:/app/google-credentials.json
    depends_on:
      - redis
      - minio
      - mongodb
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE_NAME=your_database_name

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A config.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/app
      - chromadb_data:/app/chromadb
      - ./google-credentials.json:/app/google-credentials.json
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE_NAME=your_database_name

  redis:
    image: "redis:6"
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: "minio/minio"
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    env_file:
      - ./.env

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=your_database_name

volumes:
  minio_data:
  chromadb_data:
  mongodb_data:
